pipeline {
    agent none

    options {
        durabilityHint('PERFORMANCE_OPTIMIZED') 
    }

    stages {
        stage('Hello') {
            steps {
                echo "Hello World ${myName}"
            }
        }
    }
}
